openapi: 3.0.1
info:
  title: Real Estate API
  description: API for managing real estate properties
  version: 1.0.0
servers:
  - url: https://realestate-qtw7.onrender.com
paths:
  /api/properties:
    get:
      operationId: listProperties
      summary: List all properties
      description: Get a list of all available properties
      responses:
        '200':
          description: List of properties
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Property'
    post:
      operationId: createProperty
      summary: Create a new property
      description: Add a new property listing
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PropertyRequest'
      responses:
        '201':
          description: Property created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Property'

components:
  schemas:
    Property:
      type: object
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
        description:
          type: string
        price:
          type: number
          format: double
        location:
          type: string
        propertyType:
          type: string
          enum: [HOUSE, APARTMENT, LAND, COMMERCIAL]
        images:
          type: array
          items:
            type: string
            format: uri
    PropertyRequest:
      type: object
      required:
        - title
        - price
        - location
        - propertyType
      properties:
        title:
          type: string
        description:
          type: string
        price:
          type: number
          format: double
        location:
          type: string
        propertyType:
          type: string
          enum: [HOUSE, APARTMENT, LAND, COMMERCIAL]
